# Generated by Django 4.1.2 on 2022-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('ItemImg', models.CharField(max_length=500)),
                ('Itemprice', models.IntegerField()),
                ('Rating', models.DecimalField(decimal_places=3, max_digits=5)),
                ('Category', models.CharField(max_length=250)),
                ('Best', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
